- hosts: localhost
  connection: local 
  roles:
  - oh-my-zsh
  - { role: p10k, zsh_plugin: ohmyzsh, p10k_prompt_style: lean, p10k_prompt_height: one-line }
  - { role: jet_brains_toolbox, become: true }
  - { role: docker, become: true }
  - { role: nodejs, become: true }
  - { role: kubectl, become: true }
  - { role: helm, become: true }
  - { role: azure-cli, become: true }

  tasks:
  - name: azure credential provider
    become: true
    ansible.builtin.unarchive:
      src: https://github.com/microsoft/artifacts-credprovider/releases/download/latest/Microsoft.NuGet.CredentialProvider.tar.gz
      dest: ~/.nuget/plugins
      remote_src: yes
  - name: install vscode and slack (classic)
    become: true
    community.general.snap:
      name:
      - code
      - slack
      classic: yes
  - name: install discord, teams, flameshot
    become: true
    community.general.snap:
      name:
      - discord
      - teams-for-linux
      - flameshot
  - name: Install htop
    become: true
    apt:
      pkg:
      - htop