---
- apt:
    deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    update_cache: true
  become: true

- apt:
    update_cache: true
    pkg:
    - apt-transport-https
    - dotnet-sdk-6.0
    - htop
    - xsel
    - xclip
    - gnome-shell-extensions
    - gnome-shell-extension-prefs
    - gnome-tweaks
    - gnome-tweak-tool
    - dconf-editor
    - python3-pip
    - dconf-cli
  become: true

- apt:
    deb: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
  become: true

